#!/bin/sh; C:/Program Files/Git/bin/sh.exe

PROJECT_FILE=SignalSharp/SignalSharp.csproj
VERSION_TAG=$(sed -n 's/.*<PackageVersion>\(.*\)<\/PackageVersion>.*/\1/p' $PROJECT_FILE)

TAG_NAME="v$VERSION_TAG"

# Check whether version tag exists
if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
    # tag exists, do nothing
    echo "Version $VERSION_TAG already tagged."
else
    # tag does not exist
    # add version tag
    git tag $TAG_NAME
    git push origin $TAG_NAME
    echo "Version $VERSION_TAG tagged and pushed."
fi