version: 33
jobs:
  - name: Release
    steps:
      - !CommandStep
        name: push
        runInContainer: true
        image: mcr.microsoft.com/dotnet/sdk
        interpreter: !DefaultInterpreter
          commands: |
            dotnet nuget add source --name onedev --username @secret:ci-user@ --password @secret:ci-token@ --store-password-in-clear-text @secret:package-repository-url@
            dotnet nuget push --source onedev ./nupkgs/*.nupkg
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !TagCreateTrigger {}
    jobDependencies:
      - jobName: Build and Test
        requireSuccessful: true
        artifacts: '**'
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
  - name: Pull from Github
    steps:
      - !PullRepository
        name: pull
        remoteUrl: https://github.com/emmorts/SignalSharp
        userName: emmorts
        passwordSecret: github-token
        refs: refs/heads/*
        withLfs: false
        force: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !ScheduleTrigger
        cronExpression: 0 */30 * * * ? *
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
  - name: Push to Github
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: push
        runInContainer: true
        image: alpine/git
        interpreter: !DefaultInterpreter
          commands: |
            # Define new remote URL with authentication
            
            AUTH = "emmorts:@secret:github-token@"
            
            GITHUB_REMOTE="https://${AUTH}@@github.com/emmorts/SignalSharp.git"
            
            git remote add origin-gh $GITHUB_REMOTE
            git fetch origin --all
            
            git push origin-gh --all
            git push origin-gh --tags
            
            echo "Repository has been successfully mirrored to the new remote."
        useTTY: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PushRepository
        name: push to github
        remoteUrl: https://github.com/emmorts/SignalSharp
        userName: emmorts
        passwordSecret: github-token
        force: false
        condition: NEVER
    triggers:
      - !BranchUpdateTrigger {}
      - !TagCreateTrigger
        branches: main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
  - name: Build and Test
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: test
        runInContainer: true
        image: mcr.microsoft.com/dotnet/sdk
        interpreter: !DefaultInterpreter
          commands: |
            dotnet test ./SignalSharp.Tests/SignalSharp.Tests.csproj --configuration Release
        useTTY: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: pack
        runInContainer: true
        image: mcr.microsoft.com/dotnet/sdk
        interpreter: !DefaultInterpreter
          commands: |
            mkdir ./nupkgs
            dotnet pack ./SignalSharp/SignalSharp.csproj --output ./nupkgs
        useTTY: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PublishArtifactStep
        name: publish
        artifacts: nupkgs/*
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger {}
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
